# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.servicefactory:
        class: AppBundle\Service\Factory\ServiceFactory
        arguments: ["@doctrine.orm.entity_manager"]
    app.userservice:
        class: AppBundle\Service\Declaration\IUserService
        factory: ["@app.servicefactory", getUserService ]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
