# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.servicefactory:
        class: AppBundle\Service\Factory\ServiceFactory
        arguments: ["@doctrine.orm.entity_manager"]
    app.holidayservice:
        class: AppBundle\Service\Declaration\IHolidayService
        factory: ["@app.servicefactory", getHolidayService ]
    app.userservice:
        class: AppBundle\Service\Declaration\IUserService
        factory: ["@app.servicefactory", getUserService ]
    app.takenholidayservice:
        class: AppBundle\Service\Declaration\ITakenHolidayService
        factory: ["@app.servicefactory", getTakenHolidayService ]
    app.availableholidayservice:
        class: AppBundle\Service\Declaration\IAvailableHolidayService
        factory: ["@app.servicefactory", getAvailableHolidayService]
    app.roleservice:
        class: AppBundle\Service\Declaration\IRoleService
        factory: ["@app.servicefactory", getRoleService]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
